### ISSUE TITLE
Python2 and UTC offset (%z)

### ISSUE THREAD

**Issue by k0ste** [gen1us2k/python-whois#13]
# Errors:

**Test google.jp with python2**

``` python
google.jp
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    w = whois.query(d, ignore_returncode=1)
  File "/tmp/google.jp/whois/__init__.py", line 63, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/tmp/google.jp/whois/_3_adjust.py", line 18, in __init__
    self.last_updated = str_to_date(data['updated_date'][0])
  File "/tmp/google.jp/whois/_3_adjust.py", line 82, in str_to_date
    if PYTHON_VERSION < 3: return str_to_date_py2(s)
  File "/tmp/google.jp/whois/_3_adjust.py", line 106, in str_to_date_py2
    raise ValueError("Unknown date format: '%s'" % s)
ValueError: Unknown date format: '2015/06/01 01:05:07 (+0900)'
```

**Test google.jp with python3**

``` python
google.jp
     expiration_date    "2016-05-31 00:00:00"
                name    "google.jp"
       registrant_cc    ""
           registrar    ""
        name_servers    "{'ns2.google.com', 'ns3.google.com', 'ns4.google.com', 'ns1.google.com'}"
       creation_date    "2005-05-30 00:00:00"
        last_updated    "2015-06-01 01:05:07+09:00"
```
# Testcase:

``` python
import datetime

def func(data, sample):
    try:
        return datetime.datetime.strptime(data, sample)
    except:
        raise ValueError("Unknown date format: '%s'" % data)

sample = '%Y/%m/%d %H:%M:%S (%z)'
data = '2015/06/01 01:05:07 (+0900)'

print(func(data, sample))
```

**Returns with python2:**

``` python
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    print(func(data, sample))
  File "example.py", line 7, in func
    raise ValueError("Unknown date format: '%s'" % data)
ValueError: Unknown date format: '2015/06/01 01:05:07 (+0900)'
```

**Returns with python3:**

``` shell
2015-06-01 01:05:07+09:00
```
# Fixed example:

``` python
import datetime, sys, re

def func(data, sample):

    if PYTHON_VERSION < 3:
        tmp = re.findall('\+([0-9]{2})00', data)
        if tmp:
            tz = int(tmp[0])
        else:
            tz = 0

        data = re.sub('\s\((\+)([0-9]{2})([0-9]{2})\)', '', data)
        sample = re.sub('\s\(\%z\)', '', sample)

        try:
            return datetime.datetime.strptime(data, sample) + datetime.timedelta(hours=tz)
        except:
            raise ValueError("[PYTHON2] Unknown date format: '%s'" % data)

    try:
        return datetime.datetime.strptime(data, sample)
    except:
        raise ValueError("[PYTHON3] Unknown date format: '%s'" % data)


PYTHON_VERSION = sys.version_info[0]
sample = '%Y/%m/%d %H:%M:%S (%z)'
data = '2015/06/01 01:05:07 (+0900)'

print(func(data, sample))
```

**Returns with python2:**

``` shell
2015-06-01 10:05:07
```

**Returns with python3:**

``` shell
2015-06-01 01:05:07+09:00
```

---

Seems %z is not work with python2. But in documentation is present. In code implement workaround for python2 but not fully. Or just not works on last versions of python2, don't know.
If results of second example is correct, I can prepare a patch.

**Comment by k0ste** [comment]
Fixed via #15.
