### ISSUE TITLE
NameError: name 'domain' is not defined

### ISSUE THREAD

**Issue by aleks-spv** [gen1us2k/python-whois#22]
Привет, хотел попробовать модуль, но что то не получается
установил - python-whois-extended 0.6.10

```
> root@zabbix:/home/appliance# python3
> Python 3.5.2 (default, Nov 23 2017, 16:37:01)
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import whois
> >>> domain = whois.query('google.com')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/whois/__init__.py", line 52, in query
>     pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
>   File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 40, in do_query
>     _do_whois_query(dl, ignore_returncode),
>   File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 60, in _do_whois_query
>     if not ignore_returncode and p.returncode != 0: raise Exception(r)
> Exception:    Domain Name: GOOGLE.COM
>    Registry Domain ID: 2138514_DOMAIN_COM-VRSN
>    Registrar WHOIS Server: whois.markmonitor.com
>    Registrar URL: http://www.markmonitor.com
>    Updated Date: 2018-02-21T18:36:40Z
>    Creation Date: 1997-09-15T04:00:00Z
>    Registry Expiry Date: 2020-09-14T04:00:00Z
>    Registrar: MarkMonitor Inc.
>    Registrar IANA ID: 292
>    Registrar Abuse Contact Email: abusecomplaints@markmonitor.com
>    Registrar Abuse Contact Phone: +1.2083895740
>    Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
>    Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
>    Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
>    Domain Status: serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited
>    Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
>    Domain Status: serverUpdateProhibited https://icann.org/epp#serverUpdateProhibited
>    Name Server: NS1.GOOGLE.COM
>    Name Server: NS2.GOOGLE.COM
>    Name Server: NS3.GOOGLE.COM
>    Name Server: NS4.GOOGLE.COM
>    DNSSEC: unsigned
>    URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
> >>> Last update of whois database: 2018-04-24T04:45:29Z <<<
> 
> For more information on Whois status codes, please visit https://icann.org/epp
> 
> NOTICE: The expiration date displayed in this record is the date the
> registrar's sponsorship of the domain name registration in the registry is
> currently set to expire. This date does not necessarily reflect the expiration
> date of the domain name registrant's agreement with the sponsoring
> registrar.  Users may consult the sponsoring registrar's Whois database to
> view the registrar's reported date of expiration for this registration.
> 
> TERMS OF USE: You are not authorized to access or query our Whois
> database through the use of electronic processes that are high-volume and
> automated except as reasonably necessary to register domain names or
> modify existing registrations; the Data in VeriSign Global Registry
> Services' ("VeriSign") Whois database is provided by VeriSign for
> information purposes only, and to assist persons in obtaining information
> about or related to a domain name registration record. VeriSign does not
> guarantee its accuracy. By submitting a Whois query, you agree to abide
> by the following terms of use: You agree that you may use this Data only
> for lawful purposes and that under no circumstances will you use this Data
> to: (1) allow, enable, or otherwise support the transmission of mass
> unsolicited, commercial advertising or solicitations via e-mail, telephone,
> or facsimile; or (2) enable high volume, automated, electronic processes
> that apply to VeriSign (or its computer systems). The compilation,
> repackaging, dissemination or other use of this Data is expressly
> prohibited without the prior written consent of VeriSign. You agree not to
> use electronic processes that are automated and high-volume to access or
> query the Whois database except as reasonably necessary to register
> domain names or modify existing registrations. VeriSign reserves the right
> to restrict your access to the Whois database in its sole discretion to ensure
> operational stability.  VeriSign may restrict or terminate your access to the
> Whois database for failure to abide by these terms of use. VeriSign
> reserves the right to modify these terms at any time.
> 
> The Registry database contains ONLY .COM, .NET, .EDU domains and
> Registrars.
> 
> >>> print(domain.__dict__)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'domain' is not defined
> >>>
```

**Comment by k0ste** [comment]
Please, use `python-whois` from `master` branch.
