### ISSUE TITLE
info domains not working

### ISSUE THREAD

**Issue by DmitriyLyalyuev** [gen1us2k/python-whois#3]
$ /usr/lib/nagios/plugins/check_domain -d lyalyuev.info
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_domain", line 27, in <module>
    check_domain(options.domain)
  File "/usr/lib/nagios/plugins/check_domain", line 14, in check_domain
    if (q.expiration_date - datetime.now()).days <= 30:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

**Comment by gen1us2k** [comment]
Fixed.
